#!/bin/bash

# Get a list of users with a password (excluding system users who don't log in)
# This command assumes the password hash is in /etc/shadow and looks for accounts
# that are not locked and have a shell
users_with_passwords=$(
  getent passwd | awk -F: '$7 !~ /(nologin|false)$/ && $2 != "" && $2 != "*" && $2 != "!" {print $1}'
)

for user in $users_with_passwords; do
  echo "Setting password inactivity period to 30 days for user: $user"
  chage --inactive 30 "$user"
done

echo "password inactivity set for all active users."
